server:
  port: 8080

#    url: jdbc:h2:mem:test  ????????????
#    url:jdbc:h2:~/test  ????????????????test??????
#    url:jdbc:h2:tcp//localhost/?/test ??????????h2 ???
spring:
  datasource:
    data: classpath:db/data.sql
    driverClassName: org.h2.Driver
    username: runbird
    password: 123
    platform: h2
    schema: classpath:db/schema.sql
    url: jdbc:h2:mem:dbtest
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true